quarkus:
  datasource:
    jdbc:
      url: jdbc:sqlite:ai-interactions.db
      min-size: 1

  rest-client:
#    logging:
#      scope: request-response
    ai-interactions:
      # The url will be overridden on a per-request basis
      url: http://dummy

  hibernate-orm:
    schema-management:
      strategy: drop-and-create

  langchain4j:
#    log-requests: true
#    log-responses: true
    cohere:
      api-key: ${COHERE_API_KEY}
      scoring-model:
        model-name: rerank-v4.0-fast

#  log:
#    category:
#      "org.parasol.ai.testing":
#        level: DEBUG

  openapi-generator:
    codegen:
      input-base-dir: ../openapi
      include: ai-interactions.yml
      spec:
        ai_interactions_yml:
          config-key: ai-interactions
        ai-interactions:
          initialize-empty-collections: true
          base-package: org.parasol.aiinteractions
          use-dynamic-url: true
          type-mappings:
            DateTime: Instant
          import-mappings:
            Instant: java.time.Instant

"%dev,test":
  quarkus:
    http:
      port: 8888