quarkus:
  rest-client:
    logging:
      scope: request-response
#    ai-interactions:
      # The url will be overridden on a per-request basis
#      url: http://dummy

  hibernate-orm:
    schema-management:
      strategy: drop-and-create

  openapi-generator:
    codegen:
      input-base-dir: ../openapi
      include: ai-interactions.yml
      spec:
        ai_interactions_yml:
          config-key: ai-interactions
        ai-interactions:
          initialize-empty-collections: true
          base-package: org.parasol.aiinteractions
          use-dynamic-url: true
          type-mappings:
            DateTime: Instant
          import-mappings:
            Instant: java.time.Instant