---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scorer-app-config
data:
  quarkus.datasource.jdbc.url: jdbc:postgresql://scorer-db:5432/interaction_scoring
  quarkus.otel.exporter.otlp.endpoint: http://lgtm:4318
  quarkus.otel.exporter.otlp.protocol: http/protobuf
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: scorer-db-creds
data:
  quarkus.datasource.username: aW50ZXJhY3Rpb25fc2NvcmluZw==
  quarkus.datasource.password: aW50ZXJhY3Rpb25fc2NvcmluZw==
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: scorer-db-config
data:
  POSTGRES_DB: aW50ZXJhY3Rpb25fc2NvcmluZw==
  POSTGRES_USER: aW50ZXJhY3Rpb25fc2NvcmluZw==
  POSTGRES_PASSWORD: aW50ZXJhY3Rpb25fc2NvcmluZw==
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scoring-db-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scorer-db
  labels:
    app.openshift.io/runtime: postgresql
    app.kubernetes.io/part-of: scoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: scorer-db
  template:
    metadata:
      labels:
        name: scorer-db
    spec:
      containers:
        - name: scorer-db
          image: postgres:18
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: scorer-db-config
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: db-data
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 32Mi
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: scoring-db-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: scorer-db
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: scorer-db
  type: ClusterIP
